apiVersion:appv1.0
kind:Deployment
metadata:
  name:mywebapp-deployment
spec:
  replicas:2
  selector:
    matchLabels:
      app:mywebapp
  template:
    metadata:
      labels:
        app:mywebapp
    spec:
      containers:
      - name:mywebapp-container
        image:snikithagovindu/mywebapp:local
        ports:
        - containerPort:80